### PR TITLE
Dp dev branch

### PR DESCRIPTION
**Pull request by darioperez1415**

### CODE REVIEW

**Review by NathanBlackman — DISMISSED** [review]
👍

**Review by Nissa2424 — CHANGES_REQUESTED** [review]
Rejected !!!

**Review by Meseret-G — CHANGES_REQUESTED** [review]
No change should be made to the main.js.

**Review by Meseret-G — APPROVED** [review]

**Review by Nissa2424 — APPROVED** [review]
👍

**Pull request merged**
